name: WBLite
author: [white_cola,lvxinlei]
version: 2.9.3
main: top.whitecola.wblite.WBLite
softdepend: [MiraiBukkit,WhiteList]
commands: 
  wb: 
   usage: /wb <childCmd> [args]...
permissions: 
  wb.reload: 
   default: op
  wb.sendmsg: 
   default: op 
    
