name: WBLite
author: [white_cola,lvxinlei]
version: 2.9.4
main: top.whitecola.wblite.WBLite
depend: [MiraiBukkit]
softdepend: [WhiteList]
commands: 
  wb: 
   usage: /wb <childCmd> [args]...
permissions: 
  wb.reload: 
   default: op
  wb.sendmsg: 
   default: op 
    
